In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
#loading data 
dfFake = pd.read_csv("Fake.csv")
dfTrue = pd.read_csv("True.csv")

In [3]:
#Reading first 10 row for CSV file
dfFake.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  
5  December 25, 2017  
6  December 23, 2017  
7  December 23, 2017  
8  December 22, 2017  
9  December 21, 2017

In [4]:
dfTrue.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   
5  December 29, 2017   
6  December 29, 2017   
7  December 29, 2017   
8  December 29, 2017   
9  December 28, 2017

In [5]:
#Adding a Binary classfication to the data
dfTrue["Validity"] = 0
dfFake["Validity"] = 1

In [6]:
#Checking the number of rows and columns for the dataset
dfTrue.shape, dfFake.shape

((21417, 5), (23481, 5))

In [7]:
#Merging both data into one
dfNew = pd.concat([dfTrue, dfFake], axis =0 )
dfNew.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

                 date  Validity  
0  December 31, 2017          0  
1  December 29, 2017          0  
2  December 31, 2017          0  
3  December 30, 2017          0  
4  December 29, 2017          0  
5  December 29, 2017          0  
6  December 29, 2017          0  
7  December 29, 2017          0  
8  December 29, 2017          0  
9  December 28, 2017          0

In [8]:
#Removing columns that we do not need
dfText = dfNew.drop(["title", "subject","date"], axis = 1)

In [9]:
dfText.isnull().sum()

text        0
Validity    0
dtype: int64

In [10]:
dfText.head()

text  Validity
0  WASHINGTON (Reuters) - The head of a conservat...         0
1  WASHINGTON (Reuters) - Transgender people will...         0
2  WASHINGTON (Reuters) - The special counsel inv...         0
3  WASHINGTON (Reuters) - Trump campaign adviser ...         0
4  SEATTLE/WASHINGTON (Reuters) - President Donal...         0

In [11]:
dfText.shape

(44898, 2)

In [12]:
dfText.drop_duplicates(inplace= True)

In [13]:
dfText.shape

(38647, 2)

In [14]:
#Downloading stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harrod\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
def wordProcess(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [16]:
dfText["text"] = dfText["text"].apply(wordProcess)

In [17]:
x = dfText["text"]
y = dfText["Validity"]

In [18]:
#splitting the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

Vectorizer = TfidfVectorizer()
DataTrain = Vectorizer.fit_transform(x_train)
DataTest = Vectorizer.transform(x_test)

# Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression

LogisticRegression = LogisticRegression()
LogisticRegression.fit(DataTrain,y_train)

LogisticRegression()

In [22]:
PredictLR=LogisticRegression.predict(DataTest)

In [23]:
LogisticRegression.score(DataTest, y_test)

0.984993531694696

In [24]:
print(classification_report(y_test, PredictLR))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4248
           1       0.99      0.98      0.98      3482

    accuracy                           0.98      7730
   macro avg       0.99      0.98      0.98      7730
weighted avg       0.99      0.98      0.98      7730



# Gradient Boosting Classifier

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

GradientBoostingClassifier = GradientBoostingClassifier(random_state=0)
GradientBoostingClassifier.fit(DataTrain, y_train)

GradientBoostingClassifier(random_state=0)

In [26]:
PredictGBC = GradientBoostingClassifier.predict(DataTest)

In [27]:
GradientBoostingClassifier.score(DataTest, y_test)

0.9948253557567918

In [28]:
print(classification_report(y_test, PredictGBC))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4248
           1       1.00      0.99      0.99      3482

    accuracy                           0.99      7730
   macro avg       1.00      0.99      0.99      7730
weighted avg       0.99      0.99      0.99      7730



# Random Forest Classifier

In [29]:
from sklearn.ensemble import RandomForestClassifier

RandomForestClassifier = RandomForestClassifier(random_state=0)
RandomForestClassifier.fit(DataTrain, y_train)

RandomForestClassifier(random_state=0)

In [30]:
PredictRFC = RandomForestClassifier.predict(DataTest)

In [31]:
RandomForestClassifier.score(DataTest, y_test)

0.9838292367399741

In [32]:
print(classification_report(y_test, PredictRFC))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4248
           1       0.99      0.97      0.98      3482

    accuracy                           0.98      7730
   macro avg       0.98      0.98      0.98      7730
weighted avg       0.98      0.98      0.98      7730



# navie bayes

In [33]:
from sklearn.naive_bayes import MultinomialNB


In [34]:
nb = MultinomialNB()
nb.fit(DataTrain, y_train)

MultinomialNB()

In [35]:
PredictNB=nb.predict(DataTest)

In [36]:
nb.score(DataTest, y_test)

0.93751617076326

In [37]:
print(classification_report(y_test, PredictNB))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94      4248
           1       0.96      0.90      0.93      3482

    accuracy                           0.94      7730
   macro avg       0.94      0.93      0.94      7730
weighted avg       0.94      0.94      0.94      7730



# Support Vector Machine Classifier

In [21]:
from sklearn.svm import SVC

SupportVectorMachine = SVC(kernel='linear')
SupportVectorMachine.fit(DataTrain, y_train)

SVC(kernel='linear')

In [ ]:
SupportVectorMachine.score(DataTest, y_test)

In [ ]:
PredictSVM=SupportVectorMachine.predict(DataTest)
print(classification_report(y_test, PredictSVM))

# Fine tuning SVM

In [99]:
from sklearn.model_selection import GridSearchCV
svm = SVC()
param_grid = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto']}
grid = GridSearchCV(svm, param_grid, cv=5, verbose=3)
grid.fit(DataTrain, y_train)
print("Best Hyperparameters:", grid.best_params_)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] C=0.1, gamma=scale, kernel=linear ...............................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ... C=0.1, gamma=scale, kernel=linear, score=0.983, total= 6.0min
[CV] C=0.1, gamma=scale, kernel=linear ...............................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  6.0min remaining:    0.0s


[CV] ... C=0.1, gamma=scale, kernel=linear, score=0.982, total= 6.0min
[CV] C=0.1, gamma=scale, kernel=linear ...............................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 12.0min remaining:    0.0s


[CV] ... C=0.1, gamma=scale, kernel=linear, score=0.982, total= 6.0min
[CV] C=0.1, gamma=scale, kernel=linear ...............................
[CV] ... C=0.1, gamma=scale, kernel=linear, score=0.985, total= 6.1min
[CV] C=0.1, gamma=scale, kernel=linear ...............................
[CV] ... C=0.1, gamma=scale, kernel=linear, score=0.981, total= 6.0min
[CV] C=0.1, gamma=scale, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=scale, kernel=rbf, score=0.971, total= 9.1min
[CV] C=0.1, gamma=scale, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=scale, kernel=rbf, score=0.974, total= 9.3min
[CV] C=0.1, gamma=scale, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=scale, kernel=rbf, score=0.975, total= 9.2min
[CV] C=0.1, gamma=scale, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=scale, kernel=rbf, score=0.976, total= 9.4min
[CV] C=0.1, gamma=scale, kernel=rbf ..................................
[CV] .

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed: 657.9min finished


Best Hyperparameters: {'C': 1, 'gamma': 'scale', 'kernel': 'linear'}


# deep learning algorithm LSTM

In [54]:
dfText
dfText.head()
dfText.dropna()

text  Validity
0      washington  reuters    the head of a conservat...         0
1      washington  reuters    transgender people will...         0
2      washington  reuters    the special counsel inv...         0
3      washington  reuters    trump campaign adviser ...         0
4      seattle washington  reuters    president donal...         0
...                                                  ...       ...
22698   century wire says all the world s a stage  an...         1
22699    randy johnson  century wirethe majority of m...         1
22700  tune in to the alternate current radio network...         1
22701   century wire says a new front has just opened...         1
22702   century wire says it s not that far away  gue...         1

[38647 rows x 2 columns]

In [66]:
X=dfText.drop('Validity',axis=1)
y=dfText['Validity']

In [67]:
y.value_counts()

0    21192
1    17455
Name: Validity, dtype: int64

In [68]:
X.shape

(38647, 1)

In [69]:
y.shape

(38647,)

In [47]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [70]:
voc_size=5000
messages = X.copy()
messages.reset_index(inplace=True)

In [73]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['text'][i])
    # lowering words in the particular sentences.
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [74]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 

In [75]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[ 359 1808  392 ... 2643 1525  359]
 [1065 2354    6 ... 4353  509  853]
 [2748 4803   78 ... 4808  404 1642]
 ...
 [ 714 3741 2344 ... 3521 2824 3911]
 [4923 3352 2507 ... 3297 3461 4717]
 [3516 4767 4186 ... 4805 2444 3047]]


In [76]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [77]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [78]:
X_final = np.array(embedded_docs)
y_final = np.array(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [79]:
model.fit(X_train,y_train,validation_data = (X_test,y_test), epochs = 10,batch_size = 64)

Epoch 1/10
405/405 [==============================] - 8s 16ms/step - loss: 0.1961 - accuracy: 0.9164 - val_loss: 0.1280 - val_accuracy: 0.9524
Epoch 2/10
405/405 [==============================] - 6s 14ms/step - loss: 0.0937 - accuracy: 0.9672 - val_loss: 0.1297 - val_accuracy: 0.9519
Epoch 3/10
405/405 [==============================] - 6s 14ms/step - loss: 0.0705 - accuracy: 0.9764 - val_loss: 0.1430 - val_accuracy: 0.9516
Epoch 4/10
405/405 [==============================] - 6s 14ms/step - loss: 0.0516 - accuracy: 0.9833 - val_loss: 0.1588 - val_accuracy: 0.9479
Epoch 5/10
405/405 [==============================] - 6s 14ms/step - loss: 0.0343 - accuracy: 0.9886 - val_loss: 0.2018 - val_accuracy: 0.9450
Epoch 6/10
405/405 [==============================] - 6s 14ms/step - loss: 0.0244 - accuracy: 0.9921 - val_loss: 0.2235 - val_accuracy: 0.9455
Epoch 7/10
405/405 [==============================] - 6s 14ms/step - loss: 0.0174 - accuracy: 0.9945 - val_loss: 0.2403 - val_accuracy: 0.9413

In [81]:
predictions = (model.predict(X_test) > 0.5).astype("int32")
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

399/399 [==============================] - 2s 4ms/step


0.9400188176258428

# Testing

In [ ]:
def Prediction(n):
    if n == 0:
        return "True"
    elif n == 1:
        return "False"
    
def DataTesting(article):
    TestArticle = {"text":[article]}
    newTest = pd.DataFrame(TestArticle)
    newTest["text"] = newTest["text"].apply(wordProcess) 
    newTest2 = newTest["text"]
    TestVector = Vectorizer.transform(newTest2)
    PredictSVM = nb.predict(TestVector)

    return print("\SVM Prediction: {}".format(Prediction(PredictSVM[0])))

In [39]:
article = str(input())
DataTesting(article)

donald trump like to eat

GBC Prediction: False
